# **Arrays**

Arrays are not part of the language. We will use them through the numpy library. 
Arrays are similar to lists, but all elements must be of the same type.


The numpy library provides implementations of many useful operations on arrays of any dimensionality.  

The following statement imports the library and declares np as short for numpy. We can access functions and modules in the numpy library by using the dot notation. 

In [ ]:
import numpy as np

Arrays can be created in several ways.

We can convert a list to a 1-D array.

In [ ]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


We can convert a list of lists to a 2-D array (or a list of lists of lists to a 3D array, and so on).

In [ ]:
a = np.array([[1,2,3,4],[5,6,7,8]])
print(a)

[[1 2 3 4]
 [5 6 7 8]]


Unlike Java, numpy does not allow jagged arrays. 

In [ ]:
a = np.array([[1,2,3,4],[5,6,7]])
print(a)

[list([1, 2, 3, 4]) list([5, 6, 7])]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  """Entry point for launching an IPython kernel.


The array type is infered from the data provided

In [ ]:
a = np.array([[1.5,2,3,4],[5,6,7,8]])
print(a)

[[1.5 2.  3.  4. ]
 [5.  6.  7.  8. ]]


The function zeros creates an array full of zeros, the function ones creates an array full of ones, and the function empty creates an array whose initial content is random and depends on the state of the memory. By default, the dtype of the created array is float64.

In [ ]:
a = np.zeros(5) # Create 1-D array
print(a)

[0. 0. 0. 0. 0.]


In [ ]:
a = np.zeros((5,3)) # Create 2-D array with 5 rows and 3 colummns
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
a = np.ones((2,3)) # Create 2-D array with 2 rows and 3 colummns
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


You can also specify the type

In [ ]:
a = np.ones((2,3),dtype=np.int16) # Create 2-D array with 2 rows and 3 colummns
print(a)

[[1 1 1]
 [1 1 1]]


To create sequences of numbers, NumPy provides the arange function which is analogous to the Python built-in range, but returns an array.

In [ ]:
a= np.arange(16)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [ ]:
a= np.arange(20,100,10)
print(a)

[20 30 40 50 60 70 80 90]


The reshape operation can be used to change the dimensionality of an array (but the number of elements cannot change).

In [ ]:
a= np.arange(16)
print(a)
b = a.reshape(4,4)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
a= np.arange(16)
b = a.reshape(4,5)
print(b)

ValueError: ignored

reshape returns a copy of the array, without modifying the original array.


In [ ]:
a= np.arange(16)
a.reshape(4,4)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


a.shape is a tuple (an immutable list) that contains the size of each of the dimensions of array a. len(a.shape) contains the number of dimensions of a.

In [ ]:
a= np.arange(16)
print(a)
print(a.shape)
print(len(a.shape))
b = a.reshape(4,4)
print(b)
print(b.shape)
print(len(b.shape))
c = a.reshape(2,2,4,1)
print(c)
print(c.shape)
print(len(c.shape))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
(16,)
1
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
(4, 4)
2
[[[[ 0]
   [ 1]
   [ 2]
   [ 3]]

  [[ 4]
   [ 5]
   [ 6]
   [ 7]]]


 [[[ 8]
   [ 9]
   [10]
   [11]]

  [[12]
   [13]
   [14]
   [15]]]]
(2, 2, 4, 1)
4


Arithmetic operators on arrays apply elementwise. There's no need to write for loops to perform array operations!!!

In [ ]:
a= np.arange(16).reshape(4,4)
print(a)
b = a + 5
print(b)
c = a**2
print(c)
d = np.sin(a)
print(d)
print(a+b) 
print(a*c) 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]
 [144 169 196 225]]
[[ 0.          0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155   0.6569866 ]
 [ 0.98935825  0.41211849 -0.54402111 -0.99999021]
 [-0.53657292  0.42016704  0.99060736  0.65028784]]
[[ 5  7  9 11]
 [13 15 17 19]
 [21 23 25 27]
 [29 31 33 35]]
[[   0    1    8   27]
 [  64  125  216  343]
 [ 512  729 1000 1331]
 [1728 2197 2744 3375]]


Integer indexing works the same was as in Java 

In [ ]:
print(a[2,3])
print(a[0,2])

11
2


As with lists, negative indices (counting from the end) are allowed

In [ ]:
print(a[0,-1])
print(a[-1,0])

3
12


Slicing works the same ways as with lists, with one slice per dimension

In [ ]:
print(a[:2,1:])  # Select rows 0 and 1 and columns 1,2, and 3

[[1 2 3]
 [5 6 7]]


In [ ]:
print(a[::2,1::2])  # Select rows 0 and 2 and columns 1 and 3

[[ 1  3]
 [ 9 11]]


In [ ]:
print(a[:,::-1])  # Reverse the order of columns

[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]
 [15 14 13 12]]


In [1]:
print(a[::-1,:])  # Reverse the order of rows

NameError: name 'a' is not defined

In [ ]:
print(a[::-1])  # Reverse the order of rows, trailing ':' may be ommited

[[12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


We can use lists of the same length as indices

In [ ]:
c = a[[2,3,1],[1,0,3]] # Returns 1-D array containing [a[2,1], a[3,0], a[1,3]]
print(c)

[ 9 12  7]


We can assign values to array elements and slices

In [ ]:
a= np.arange(16).reshape(4,4)
print(a)
a[2,3] = -100
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[   0    1    2    3]
 [   4    5    6    7]
 [   8    9   10 -100]
 [  12   13   14   15]]


In [ ]:
a= np.arange(16).reshape(4,4)
print(a)
a[:2,1:] = -100
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[   0 -100 -100 -100]
 [   4 -100 -100 -100]
 [   8    9   10   11]
 [  12   13   14   15]]


You can perform elementwise operations on array slices if they are the same size

In [ ]:
a= np.arange(16).reshape(4,4)
print(a)
b = np.arange(6).reshape(2,3)
print(b)
a[:2,1:] = a[:2,1:] - b
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0 1 2]
 [3 4 5]]
[[ 0  1  1  1]
 [ 4  2  2  2]
 [ 8  9 10 11]
 [12 13 14 15]]


Warning - arrays are passed by reference; array assignments are shallow

In [ ]:
a= np.arange(16).reshape(4,4)
print(a)
b = a
b[0,0] = 2302
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[2302    1    2    3]
 [   4    5    6    7]
 [   8    9   10   11]
 [  12   13   14   15]]


This will make a deep copy of a

In [ ]:
a= np.arange(16).reshape(4,4)
print(a)
b = np.copy(a)
b[0,0] = 2302
print(a)
print(b)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[2302    1    2    3]
 [   4    5    6    7]
 [   8    9   10   11]
 [  12   13   14   15]]


Numpy provides LOTS of array operations. See:
https://numpy.org/doc/stable/reference/routines.math.html

Commonly use built-in functions:


In [ ]:
a = np.array([60,  0, 70, 50, 10, 30, 90, 40, 80, 20])

In [ ]:
print(np.min(a))

0


In [ ]:
print(np.max(a))

90


In [ ]:
print(np.mean(a))

45.0


In [ ]:
print(np.argmax(a)) # Returns the index of the maximum element in a

6


In [ ]:
print(np.argmin(a)) # Returns the index of the minimum element in a

1


Since Python is an interpreted language, loops are slow. See the comparative running time of the same operation with and without loops. 

In [ ]:
import time

def sum_array_loops(a,b): 
  c = np.zeros_like(a) 
  for i in range(a.shape[0]):
    for j in range(a.shape[1]):
      c[i,j] =  a[i,j] + b[i,j]
  return c

def sum_array(a,b): 
  c = a +b
  return c
  
size = 2000

a = np.random.random((size,size))
b = np.random.random((size,size))

start = time.time()
c = sum_array_loops(a,b)
elapsed_time1 = time.time() - start
print('elapsed time using loops', elapsed_time1,'secs')

start = time.time()
c = sum_array(a,b)
elapsed_time2 = time.time() - start
print('elapsed time without loops', elapsed_time2,'secs')

print('ratio',elapsed_time1/elapsed_time2)

elapsed time using loops 2.4381954669952393 secs
elapsed time without loops 0.008878469467163086 secs
ratio 274.61889417009047


# **Exercises**


Write the function replace_max(a,m) that replace the maximum element in a by m. If the maximum occurs multiple times, replace only the first occurrence.

Write the function is_square(a) that receives an array a and determines if a is square (that is, is has exactly two dimensions and they have the same size).


In [ ]:
def is_square(a):
  return len(a.shape) == 2 and a.shape[0]==a.shape[1]

In [ ]:
a = np.arange(16)
print(a)
print(is_square(a))
b = a.reshape(2,8)
print(b)
print(is_square(b))
c = a.reshape(4,4,1)
print(c)
print(is_square(c))
d = a.reshape(4,4)
print(d)
print(is_square(d))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
False
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]
False
[[[ 0]
  [ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]
  [ 7]]

 [[ 8]
  [ 9]
  [10]
  [11]]

 [[12]
  [13]
  [14]
  [15]]]
False
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
True


In [ ]:
def  replace_max(a,m):
  a[np.argmax(a)] = m

In [ ]:
a = np.array([20, 90, 80, 70, 40,  0, 50, 60, 30, 10])
print(a)
replace_max(a,-1)
print(a)

[20 90 80 70 40  0 50 60 30 10]
[20 -1 80 70 40  0 50 60 30 10]


Write the function diagonal(a) that receives a square array a and returns a 1D array contaiing the elements in the diagonal of a (that is [a[0,0], a[1,1], ...).

In [ ]:
def  diagonal(a):
  d = np.arange(a.shape[0])
  return a[d,d]

In [ ]:
a = np.array([[10, 70, 40], [ 0, 80, 60], [50, 30, 20]])
print(a)
print(diagonal(a))

[[10 70 40]
 [ 0 80 60]
 [50 30 20]]
[10 80 20]
